### ISSUE TITLE
Background music does not work on Linux (as far as I know).

### ISSUE THREAD

**Issue by surajkhati** [jeezcalmdown88/AimClickBoom#1]
So, I installed Linux Mint on my machine and when I wanted to test my game again, Python threw me this error:
```
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    sounds = SoundClass()
  File "main.py", line 96, in __init__
    self.bg_music = pygame.mixer.music.load('bg_music.mp3')
pygame.error: Unrecognized audio format
```
So, I'm commenting out the lines that play music.

**Comment by surajkhati** [comment]
Done.
